### ISSUE TITLE
lower() messes with urls that require capital letters

### ISSUE THREAD

**Issue by botronic** [kaszim/desktop-stream-viewer#161]
Capitalization matters in URLs. This might explain why youtube is not working anymore, since they use capital letters in their URLs.

**Comment by botronic** [comment]
Why is lower case important?

**Comment by mictab** [comment]
Because it means that we don't have to worry about special cases when querying urls later on. E.g. if we have two urls entered by the user, e.g. "http://google.com" and "http://GOOGLE.COM" only one of them would return true for `if 'google' in url` but both of those are perfectly valid urls. Youtube stream urls seem to be a special case that can't be lower cased.
