### ISSUE TITLE
Problems with PyQt version in requirements.txt

### ISSUE THREAD

**Issue by svenanderzen** [kaszim/desktop-stream-viewer#66]
@mictab had this problem when trying to do a clean install. Said that the version of PyQt no longer exist?...

**Comment by mictab** [comment]
Yes, seems as we just got this in Travis:

`pip.exceptions.DistributionNotFound: No matching distribution found for pyqt5==5.8.1.1`

@svenanderzen @kaszim

**Comment by mictab** [comment]
So... initial thoughts. I think this is a thing with e.g. Ubuntu where you seem to do `sudo apt-get install python3-pyqt5` instead of including it in the requirements file. Options...

1. OS specific requirements in the repo
2. setup.py file where we check the OS
3. Screw everything that's not Linux and have everyone use the VM

**Comment by svenanderzen** [comment]
4. Update to 5.8.2 in the requirements.txt and act like it's raining until the next time it happens?

**Comment by mictab** [comment]
Let's try it I guess.

**Comment by svenanderzen** [comment]
We'll that worked like shit, at least on Ubuntu. 

On Fedora, installing PyQt via pip works flawlessly. However it doesn't work on Ubuntu. The user has to install the PyQt package using `apt-get install python3-pyqt5`

**Comment by svenanderzen** [comment]
Since this is probelm specific to Ubuntu, I'll close this for now.
